version: '3'

networks:
  internal:

services:
  mongo:
    networks:
      - internal
    image: 'mongo:4.4.6'
    container_name: 'mongo'
    ports:
      - '27017:27017'
  grpc-gateway-project:
    ports:
      - '8080:8080'
      - '8000:8000'
    build : .
    env_file:
      - ./.env
    volumes:
      - ./:/app
    networks:
      - internal